### ISSUE TITLE
Improve Candli + Sequence player UX

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#113]
(Low priority)

When I was playing the first math , there was still this small icon/button from Candli:
![image](https://github.com/pila-project/pila-platform/assets/145113767/3df6eaa2-fb89-45ea-951a-9cd93f338391)

I clicked it to see what would happen and it gave me this screen:
![image](https://github.com/pila-project/pila-platform/assets/145113767/47c9c622-3d1a-408d-a87c-9cd9aef466e9)

Desired functionality:
-when you hit 'begin', the game goes full screen (particularly useful for ipad and tablet because smaller screens). To go back to the sequence wrapper, the students have this small icon. 

If too complex to integrate given the sequence wrapper functionalities, we can remove for now.

**Comment by stephanemagnenat** [comment]
The map button is supposed to go back to the sequence, as the PILA game is supposed to be played in fullscreen. Candli PILA Play first checks whether fullscreen is supported, and if so, triggers a switch to fullscreen. Now actually there is a flag that disables fullscreen on Safari (because Safari puts an annoying "go out of fullscreen button near the top left"), so probably you are hitting this one (you tested with iPads right?). I've changed the code, to ignore the Safari check. Can you try again on an iPad (for example [this game](https://cand.li/dev/testing-release-pila/pila-play.html?game=e86dfc597c04587b9348952bfdcb76b1)), and then we can adjust the UI position of the map icon.

**Comment by stephanemagnenat** [comment]
I fixed the Candli side of things, now on my iPad the link above goes to fullscreen. If now it doesn't work on PILA, then it is probably an iframe settings.

**Comment by stephanemagnenat** [comment]
According to tests by @OECDPILA it works outside PILA but not within. @jasonford could it be that the Candli iframe doesn't have the `allowfullscreen` attribute set?

**Comment by Danielalopez0797** [comment]
Same screen that @OECDPILA mention, appears when returning to student PILA main page from Betty's Brain.
<img width="932" alt="Screenshot 2024-05-03 145239" src="https://github.com/pila-project/pila-platform/assets/168447956/9c073b0d-9fb2-4be3-902b-f6195fa0b8e9">

**Comment by stephanemagnenat** [comment]
So this is a PILA issue, not a Candli one. @OECDPILA can you please update the issue title?

**Comment by jasonford** [comment]
@stephanemagnenat I have fixed the fullscreen behavior for the main pila app!

After toying around with the sequence movement, I think I understand a good event flow:

1) launch fullscreen on click "begin" (currently implemented)
2) user plays and can toggle full screen at will by clicking map button (simply toggle fullscreen instead of doing that Agent.close() call...)
3) if user completes the game, exit full screen then call Agent.close({ success: true }) (necessary to exit full screen so our progress modal shows)

I think that flow will work well, and feel natural to the user for entering/exiting full screen on different interactions. Apologies if that is what you were mentioning as a good flow while we were implementing, I was halfway between code world and user flow thinking!

As an alternative to { success: true }, if you could send { competencies: {...whatever data form is convenient for you to send competencies in} }, then I can make it so that the modal shows the mini competency dashboard instead of the rather out of place "success" modal i.e.:

![0](https://github.com/pila-project/pila-platform/assets/1317275/3fcb720e-6f90-4bc3-bd5b-175b9a3a8535)

Let me know if that flow makes sense, I hope its an easy update!

**Comment by jasonford** [comment]
@stephanemagnenat having the same 2 -> 3 behavior outlined above for the candli tutorial from before + the other levels (https://pila.cand.li/pila.html?tutorial https://pila.cand.li/pila.html?level1 etc.) would be great as well since I'm putting them into the new sequences for the demo now.

Also, one tweak if possible on those original candli tasks would be to call Agent.close() with a { success: true } parameter when they click "Return To Map" after successfully completing the tutorial (Also, perhaps relabeling that button as "Continue" might make it make more generic sense for different contexts).

Let me know if you have time for this, otherwise, I think it is still functional enough for now.

**Comment by OECDPILA** [comment]
@jasonford - Can we please signal your comment about the mini competency dashboard as High Priority (or possibly move it to a new issue ticket)? We did user testing today with the team and it became quite clear that the best user experience across all science and math games would be to show the student dashboard to the student at the end of the game (to make it clear they can either a) retry if not satisified with their work or b) move on to next task (this was very confusing for most). As it stands currently, everyone was quite confused on how they did and how/when to move on to next task. From what I understand from @stephanemagnenat, all of the information that you would need for the mini competency dashboard is already being reported. The only thing left to do would be to create the little modal and program the stars to appear based on aggregated thresholds of the "sub-goals" in the task. I am fine with 3 stars = 90% and above, 2 stars = 75% and above and 1 star=50% and above (and 0 stars for anything else). Ideally all three stars will be always visible but only when they earn the stars will they be filled in with yellow. Thanks so much!!

**Comment by stephanemagnenat** [comment]
Thank you for fixing the Dashboard!

Regarding the sequence, I have adjusted the behavior of the "map" button and also exiting full-screen and reporting close to the agent on "game over" in PILA play. Shouldn't we use a fullscreen toggle icon instead?

Regarding the dashboard, it is not realistic in the short term to send `{ competencies: {...` on close because these are defined in another script block, and also sent progressively. What I suggest to do, and that was the original design I had in mind for the "student dashboard", is for the latter to fetch the skills for this current game and user, and display them. It would then show the progress "of all times" for this game rather than the last one, which might in a way be more consistent with the logic of always taking the max of existing and new value when writing competencies. Do you think that it is doable? Most code can be ripped from the competency dashboard!

Regarding the editor-based PILA levels, making the back button (changed to the map button for PILA) toggle a fullscreen instead of quitting that screen is not trivial. I do not want to risk breaking things just right now with a significant refactoring. So what I did is to add the getting out of fullscreen behavior and also pass the `{success: true}`  when the activity is completed, and an empty object `{}` otherwise (I can pass something else of course). I also changed the name of the last button. Would that work for now? I'm also happy to change the icon to not induce confusion. We could even go back to the original icon, which is a left pointing triangle ◀.

**Comment by stephanemagnenat** [comment]
> I am fine with 3 stars = 90% and above, 2 stars = 75% and above and 1 star=50% and above (and 0 stars for anything else). Ideally all three stars will be always visible but only when they earn the stars will they be filled in with yellow. Thanks so much!!

Note that the [`SuccessBox.vue` component in the competency dashboard](https://github.com/pila-project/pila-competency-dashboard/blob/main/src/components/SuccessBox.vue) provides the necessary code, including styling. It can certainly be ripped and adjusted accordingly. The star SVG themselves are [in the assets](https://github.com/pila-project/pila-competency-dashboard/tree/main/src/assets).

**Comment by jasonford** [comment]
@stephanemagnenat Thanks! I think with those changes I can smooth out the UX with the sequence, as well as add the feedback modal. There is a bit more hacking to do to make it work since I'm going to need to pull in data from parsed and reformed ids (this does bring up interesting systematic things around reporting competencies between systems smoothly and in an easy to explore/use way... but we'll save that fun stuff for later). Will close this soon!

**Comment by stephanemagnenat** [comment]
I'm very open to discuss how Candli can help supporting system-agnostic competencies reporting! I guess that's an item to discuss after the workshop indeed!

**Comment by jasonford** [comment]
@stephanemagnenat We saw that on the first Chirpy bird level success doesn't get passed when we succeed. You can inspect the close info for the first chirpy bird with this link https://embed.knowlearning.systems/7d7c4c3b-e7a1-4588-bb78-a859fffccfac (currently showing nothing on close because close info is undefined).

Just flagging in case you didn't expect that. For our integration right now we'll be gauging success from the competency data anyway, so no worries about adding close info. Just wanted to note the info passed currently. It might still be nice to differentiate the modal we show based on success for the latest run in the future though.

**Comment by jasonford** [comment]
Oh, also noncritical, if is convenient to update the map icon to the full-screen icon, I did like that suggestion of yours!

**Comment by jasonford** [comment]
All should be implemented with https://github.com/knowlearning/matching/pull/54 !

@stephanemagnenat @OECDPILA Please open a new issue if anything is missing or off.

**Comment by OECDPILA** [comment]
THANK YOU @jasonford ! This is awesome:

![image](https://github.com/pila-project/pila-platform/assets/145113767/396fa80e-9fe1-46b1-8aa5-45b7d320bae2)

**Comment by stephanemagnenat** [comment]
I have updated the icon!
