### ISSUE TITLE
Chirpy bird tasks push you out (saying you've completed the task) even when you haven't

### ISSUE THREAD

**Issue by vs-ranjani** [pila-project/pila-platform#131]
In Chirpy bird tasks on PILA, I am sometimes pushed out of the task and moved to the next one in the sequence even when I haven't finished it

**Comment by jasonford** [comment]
@vs-ranjani was this after completing the map/losing 3 lives or just randomly?

**Comment by jasonford** [comment]
If it is after close/lose a life, this can probably be tracked with: https://github.com/pila-project/pila-platform/issues/113

**Comment by stephanemagnenat** [comment]
I think that we identified this during our discussion with OECD this afternoon to be a "normal" behavior when all lives are lost in Chirpy bird (each collision removes a life, and there are only 3), the game closes, as it is "game over", although the level is not finished. Indeed #113 will help there.

One question is whether the sequence should go to the next task "automatically" (does it do that?) if less than 3 stars are reached. From a naive UX perspective, I would say that if the task is perfectly completed (all items fulfilled), progression should be automatic, otherwise it should be a decision of the user. But I might not have a complete view of the question so take this input with a grain of salt.

**Comment by OECDPILA** [comment]
Yes, I agree with @stephanemagnenat on moving to the next task in the sequence automatically (if the task is perfectly achieved), otherwise it should be a decision of the user. This will be specific to the new candli games for the workshop since we don't have a "retry" button for linguistic items (simpler item types). Eventually, as we discussed in previous meetings, we want to surface the option for the sequences to be for assessment (no feedback on individual items) OR for learning (feedback and possibility to retry) - this option would be exposed at the **assignment level** in the PILA teacher interface.

**Comment by stephanemagnenat** [comment]
We briefly discussed with @OECDPILA offline and the consensus is that on the long term there could be a task setting about whether it is a test (go forward whatever the result), or a training (allow to retry). This setting could be exposed to the sequence author. For now it is ok to hard-code the behavior depending on the type of task (Candli games vs not Candli games).

**Comment by jasonford** [comment]
Makes sense. I'll implement that flow. Thanks for the discussion!

**Comment by jasonford** [comment]
Behaviors fixed on sequence wrapper side with: https://github.com/knowlearning/matching/pull/54
