### ISSUE TITLE
Creator App Thai Translations - Further suggestions

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#145]
(High Priority)

I received feedback that the new Thai translations are not fully correct in the menu of the creator app tool. Our colleague sent over this document with clarifications in red.
[translations proposal (002).docx](https://github.com/pila-project/pila-platform/files/15253222/translations.proposal.002.docx)

Thanks a lot!

**Comment by mthomasmcclain** [comment]
The fix on page one is done.

For page two, what I need is the names of those tags in English and Thai next to each other. (Similar to what Emma had sent before).  The reason is that the tag(s) that get applied to those sequences are actually just uuids ('abc-123'), and then that id has both English and Thai display/translation.

**Comment by OECDPILA** [comment]
@mthomasmcclain thanks Matt ! I already integrated the sequences on page 2 and started the tagging work. I will send the full list of tags with english and thai later today (pending some other input from the translator).
