### ISSUE TITLE
Multiple issues with the PILA Create app 

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#167]
We are not sure whether it was the connectivity, or some persistent bugs in the platform (this strange one where you click add and then it opens the playable version rather than the customisable version...). Many people created items and then lost their work. An hour or so after the session all of the drafts showed up for some, but we are not sure if this occurred for everyone.

Within each tool, there were several bugs in terms of being able to upload files (e.g. order item type) and the image not being able to move from the right-hand column to the left-hand column in the matching item. I believe Mario wrote to Eren with a few more...

**Comment by jasonford** [comment]
@OECDPILA was the symptom of the data loss that they created an item, edited it, then refreshed the page and the item was no longer in the side menu? I have been debugging this issue, and think I have a simple explanation and targeted fix in the works for that behavior. If this is the case, the good news is that no data was actually lost, but the system we use to link them back to their data might have a bug.

**Comment by OECDPILA** [comment]
@jasonford Yes, exactly. Thanks for taking a look and identifying this possible bug!

**Comment by jasonford** [comment]
@OECDPILA sure thing! I'm keeping an eye on the system to make sure it stays up for now and holding back on deploying the deeper change until a less critical time. I'll close this issue here since the deep change is now tracked here: https://github.com/knowlearning/platform/issues/25

I see @mthomasmcclain already merged @erenkahraman's update for the issue you mentioned in the create app. Please open new issues for any other bugs you saw as you see fit.
