### ISSUE TITLE
Would it be possible to surface the 'Minimum Grade' tag with its sub-tags and content in the Item library ?

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#168]
(High Priority)

The tag 'Minimum Grade' ID is: cd0111b0-1460-11ef-ba53-17065acfcb5b

**Comment by jasonford** [comment]
Sure thing! I did it, then noticed that you might have tried to add some uuids for candli content.

That was causing a little issue where instead of tagging candli content it was creating a tag with the uuid of the candli content as a name (candli removes the "-" character from the uuids, so the behavior of the tagging app is to create a new tag with that as the name since it doesn't recognize that uuid format). If you want to tag the thai candli content, you'll need to use the UUID of the embedded content you made for the Candli items (you can go to embed.knowlearning.systems, and clicking on any of your items will put its uuid in the address bar. Also, you can drag and drop an item from the embed site list and drop the uuid).

So I'd recommend removing all the taggings you made on the "Minimum grade" tags, then adding taggings for the embed content you have.

Once you do that, you should be able to just add a tagging for "Minimum Grade" under "PILA Competencies" and the "Minimum Grade" tag will show up in the app. (The app just pulls and shows all tags under "PILA Competencies").

Whew, that was a lot of steps, but I think each one might be part of a pretty reliable and generic process/workflow that helps us in the future!

**Comment by mthomasmcclain** [comment]
@OECDPILA PS -- Remember we need the Thai translations, too. (It's easy for us to associate the tag translations with the tag ids once we have both.)

**Comment by jasonford** [comment]
@OECDPILA also, I'm happy to do it on my end/do a live session if it helps you! Just let me know

**Comment by OECDPILA** [comment]
Thanks @jasonford  - your instructions were very clear! I finalised re-tagging the Candli content. P2-P5 do not need to be translated (primary = Prathom). As for minimum grade, can you please translate to: เกรดขั้นต่ำ @mthomasmcclain  Thank you!
