### ISSUE TITLE
Add a "trainer" page in the sub-menu of teacher accounts that allows them to grant access to teachers (and other trainers)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#62]
(Before 22 May)

We will need this for the trainer workshop in Surin (by 22 May)

- [x] Surface a way for teachers to "request" the trainer role (assuming they already have a teacher account...).
- [x] Provide option to admins to move teachers to trainer roles without necessarily receiving a request from them

**Comment by jasonford** [comment]
@OECDPILA We've added a way for teachers to specify their trainer when requesting a teacher role. Their trainer can upgrade them to a trainer in the "Trainer" tab in the original trainer's thailand.pilaproject.org/teacher page. Trainers will see everyone they have added as a teacher, as well as who they have upgraded to trainer, and any teacher or trainer assignments their "child" teachers have made. Also on the "Trainer" tab is the ability to remove teacher status.

PILA admins can toggle the teacher and trainer status of anyone.

I think the functionality works pretty well right now, but the patterns could probably use some refinement to make sure they are maximally understandable/useful.

In any case, I think we have a good foundation set up, but I'll leave this issue open to discuss different views/presentations for the trainer functionality

**Comment by OECDPILA** [comment]
Thanks for this @jasonford ! Most of the participants have added me as their trainer. However, I do not see anything in my teacher account about trainers. Am I missing something, or perhaps it hasn't updated yet? I am planning to onboard three "trainers" for the Surin province on Monday so they understand the functionalities. Let me know if a quick sync up is useful! I Will be sure to get their contact information in case the designs change...

**Comment by jasonford** [comment]
@OECDPILA with the trainer update, I added an extra dropdown where a role requester selects a trainer when requesting a role. Maybe they requested teacher status before that dropdown was deployed? I see a few current role requests for teacher, but none that specify a trainer.

As things stand for now, you can claim a teacher to be in your trainer tab in your teacher account by clicking the "ADD YOUR TEACHER" button and pasting in their user id. This will establish you as their trainer, and you'll see them pop up in the table of "Your Teachers." From there, you can toggle their trainer status.

To get any user's id, you can either get it from the role requests table, or if they are already in the admin account teachers table you can actually highlight part of their name there and drag and drop it into the address bar. That will give you their teacher id.

Happy to hope on a late call tonight/this morning of yours if that will help!

**Comment by OECDPILA** [comment]
@jasonford thanks! Assigning trainer to the different teachers worked for most people because the dropdown was already there! What I am not seeing is the trainer tab in my teacher account (see screenshot):
![image](https://github.com/pila-project/pila-platform/assets/145113767/5998d513-b8d3-4e4e-ba98-7117d7b83571)

**Comment by jasonford** [comment]
Thanks for the update! Ah, I see, @OECDPILA , it looks like 13 people selected your personal account as their trainer and your personal account was marked as a trainer by EDU PILA it looks like. I have added EDU PILA as a trainer too now, so you should see that tab in the EDU PILA account. Also, I believe you should see the tab in your personal account and will see the outstanding role requests that target you (I believe there is just 1 that hasn't been made a teacher yet. The other requests were granted by EDU PILA on the admin page it looks like, so they will appear as teachers under that account in the newly available "trainer" tab). Hope this helps!

I think we have some thinking to do around making all this as clear as possible, so definitely welcome all feedback! One thing to note is that the EDU PILA account is an admin, but with this new trainer tag we've introduced the concept that even admins need to be explicitly granted attributes like "trainer." Admins are allowed to grant any of these kinds of attributes, while there are restrictions for others (like: must be "trainer" to make a "teacher")

PS. I was mistaken about the trainer missing from requests since there was a bug on the admin panel that was showing the incorrect trainer (it was showing the currently logged in admin user as the trainer instead of the real one). Definitely a cause of confusion, but fixed now!

**Comment by OECDPILA** [comment]
Thanks Jason - I think I must've assigned trainer status to my personal account in a half-asleep state haha This makes sense, and thanks again for rectifying. I will be assigning four new trainers for the Surin province today/tomorrow.

**Comment by mthomasmcclain** [comment]
was done a while ago i believe, but never closed
