### ISSUE TITLE
UX for Candli maps - any way to remove 'play game' button/screen (first screenshot) at the beginning of each task (given we already have 'home' screens for each game?)

### ISSUE THREAD

**Issue by OECDPILA** [pila-project/pila-platform#81]
(Medium priority)

![image](https://github.com/pila-project/pila-platform/assets/145113767/76e7ff3c-a4f9-4481-9df6-78457176815f)
![image](https://github.com/pila-project/pila-platform/assets/145113767/0ce38ea5-1097-4c52-966b-c046ff98559d)

**Comment by jasonford** [comment]
@OECDPILA that play screen is on the cand.li side, so would be good to get @stephanemagnenat s input on this update

**Comment by stephanemagnenat** [comment]
Indeed this feature request is fully on the Candli side, maybe there is a need for a "foreign issue" tag?

The play button is here to allow to initialize audio on a user action. Without the play game button, audio is unlikely to work in a robust way (or at all), because the web standard says that the audio context must be initialized on a user action.

We could in theory delay the initialization until the first user input (e.g., clicking away the first title screen), but that would delay loading audio (so no music in the title screen), and extra care would be needed to avoid audio glitches (as audio decompressed and the audio graph built while the game is running). Note that the title screen is using normal game code, and is no different from any other screen (it is shown with an `init` condition, the Candli equivalent of a constructor).

I'm happy to discuss possible improvements. The most realistic option I believe is to allow the game creators to define custom load screens that are shown *instead* of the play button. In that case, I'm happy to collect requirements/wishes for such screens (e.g., what to do with the unknown screen aspect ratio at the usage site, etc.).

**Comment by OECDPILA** [comment]
@stephanemagnenat thanks for the detailed description. I am fine to leave the screen for now and hear from the teachers. Could we simply make this first screen white and make the button look more like a button (perhaps using the PILA blue as an outline) and change the wording to 'begin' or 'enter' (to avoid the user having to hit 'play' twice)? Happy to discuss further.

**Comment by stephanemagnenat** [comment]
Yes I can restyle the initial button, can you show a screenshot of what you wish to have?

**Comment by OECDPILA** [comment]
![image](https://github.com/pila-project/pila-platform/assets/145113767/376ae46c-11f3-43f2-a701-6100abb50b38)

Something like this?

**Comment by jasonford** [comment]
Looks to be implemented. Thanks @stephanemagnenat !
